### ISSUE TITLE
Overcommit --sign not working

### ISSUE THREAD

**Issue by Startouf** [sds/overcommit#499]
Here's what I do on my terminal

```
> Cyril$ overcommit --sign
Updating signature for configuration file...
> Cyril$ git commit -m "overcommit stuff"
Unable to load configuration from '/[...]/.overcommit.yml': Signature of configuration file has changed!
Run `overcommit --sign` once you've verified the configuration changes.
```

This happened first after I tried to checkout a branch/commit long before I had added overcommit.

I have tried to 
- Update overcommit
- Add comments in the overcommit.yml file
- Add instructions to the overcommit.yaml file

The only fix I found thanks to a previous issue, was to remove the overcommit file, but the I'm having a lot of pain trying to merge/rebase branches

**Comment by sds** [comment]
Hey @Startouf, sorry for the confusion here.

Can you confirm whether or not you have specified the `gemfile` option in your `.overcommit.yml` (or just share your entire `.overcommit.yml` here)?

That may help us diagnose this issue. Thanks!

**Comment by campbecf** [comment]
Running into the same issue maybe? 

```
$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   app/controllers/api/generic_controller.rb

$ git commit -m "Testing"
Unable to load configuration from '/Users/user/Sites/test/.overcommit.yml': Signature of configuration file has changed!
Run `overcommit --sign` once you've verified the configuration changes.

$ overcommit --sign
Updating signature for configuration file...

$ git commit -m "Testing"
Unable to load configuration from '/Users/user/Sites/test/.overcommit.yml': Signature of configuration file has changed!
Run `overcommit --sign` once you've verified the configuration changes.
```

.overcommit.yml
```
# Use this file to configure the Overcommit hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/brigade/overcommit/blob/master/config/default.yml
#
# At the topmost level of this YAML file is a key representing type of hook
# being run (e.g. pre-commit, commit-msg, etc.). Within each type you can
# customize each hook, such as whether to only run it on certain files (via
# `include`), whether to only display output if it fails (via `quiet`), etc.
#
# For a complete list of hooks, see:
# https://github.com/brigade/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/brigade/overcommit#configuration
#
# Uncomment the following lines to make the configuration take effect.

PreCommit:
  ALL:
    problem_on_unmodified_line: warn
    exclude:
      - 'client/bower_components/**/*'
      - 'client/dist/**/*'
      - 'client/tmp/**/*'
      - 'client/node_modules/**/*'
      - 'client/public/**/*'
      - 'vendor/**/*'
      - 'tmp/**/*'
      - '.bundle/**/*'
      - '.vscode/**/*'
      - '**/*.md'

  Reek:
    enabled: true
    command: ['bundle', 'exec', 'reek']
    exclude:
      - 'db/migrate/**/*'

  # Style Check
  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop', '-c', './.rubocop.yml']

  BundleCheck:
    enabled: true

  # Speed check
  Fasterer:
    enabled: true
    command: ['bundle', 'exec', 'fasterer']

  CaseConflicts:
    enabled: true

  JsonSyntax:
    enabled: true

  LineEndings:
    enabled: true

  RailsBestPractices:
    enabled: true
    command: ['bundle', 'exec', 'rails_best_practices']

  # Migration Check
  RailsSchemaUpToDate:
    enabled: true

  # Checks for hard tabs in files
  HardTabs:
    enabled: true

  # YAML Check
  YamlSyntax:
    enabled: true

  TrailingWhitespace:
    enabled: true

  BundleAudit:
    enabled: true
    command: ['bundle', 'exec', 'bundle-audit']
    on_warn: fail

  ScssLint:
    enabled: true
    command: ['bundle', 'exec', 'scss-lint']

  CssLint:
    enabled: true
    command: ['client/node_modules/.bin/csslint']

  EsLint:
    enabled: true
    required_executable: 'client/node_modules/.bin/eslint'
    include:
      - 'client/**/*.js'

CommitMsg:
  ALL:
    on_warn: fail
    exclude:
      - 'client/bower_components/**/*'
      - 'client/dist/**/*'
      - 'client/tmp/**/*'
      - 'client/node_modules/**/*'
      - 'vendor/**/*'
      - 'tmp/**/*'
      - '.bundle/**/*'
      - '.vscode/**/*'

  HardTabs:
    enabled: true

  CapitalizedSubject:
    enabled: false

PostCheckout:
  BundleInstall:
    enabled: true

PrePush:
  # Security Check
  Brakeman:
    enabled: true
    command: ['bundle', 'exec', 'brakeman']
    flags: ['--exit-on-warn', '--quiet', '--summary', '-4', '-w3']
    on_warn: fail
    exclude:
      - 'client/bower_components/**/*'
      - 'client/dist/**/*'
      - 'client/tmp/**/*'
      - 'client/node_modules/**/*'
      - 'vendor/**/*'
      - 'tmp/**/*'
      - '.bundle/**/*'
      - '.vscode/**/*'
```
