### ISSUE TITLE
Target a subdirectory within hook config

### ISSUE THREAD

**Issue by scudco** [sds/overcommit#565]
I have mono-repo consisting of a few different projects (one rails, two ember projects, and an ember addon). I had to manually configure separate linter tasks for the ember projects, but the rails project was living at the root until recently. After moving the rails project out of the root directory pre-push hooks like `rspec` won't work because the specs actually need to be run from within the rails project's subdirectory, but overcommit assumes it should run rspec at the root. I haven't figured out a way to configure specific hooks to run from within a subdirectory.

Here's an example of one of my custom linter hooks:

```ruby
# .git-hooks/pre_commit/foo_es_lint.rb
# frozen_string_literal: true

require 'English'

module Overcommit::Hook::PreCommit
  class FooEsLint < Base
    def run
      output = `cd foo; yarn lint`
      return :fail, output unless $CHILD_STATUS.success?

      :pass
    end
  end
end
```

Is the only solution here to repeat the pattern with my per-ember project linting tasks and create a custom rspec hook that cd's into the rails directory and manually kicks off rspec?

I think ideally, I'd like to have my `.overcommit.yml` look _something_ like

```yml
PreCommit:
  RuboCop:
    enabled: true
    working_directory: 'rails_project'
  EsLint:
    name: 'Foo ESLint'
    enabled: true
    working_directory: 'ember_project_foo'
  EsLint:
    name: 'Bar ESLint'
    enabled: true
    working_directory: 'ember_project_bar'
...
PrePush:
  Brakeman:
    enabled: true
    working_directory: 'rails_project'
  RSpec:
    enabled: true
    working_directory: 'rails_project'
```

Is this ridiculous? Does it make any sense? I'd be happy to try to tackle this feature in a PR if it's worth pursuing, but maybe there's a configuration or technique I'm totally overlooking that can already accomplish this. Or maybe this is a misuse of the gem entirely? Let me know what you think.
