### ISSUE TITLE
Can't run custom commit-msg hook from overcommit

### ISSUE THREAD

**Issue by camiloforero** [sds/overcommit#658]
I am trying to run a custom commit-msg hook, CommonCommit for my project, but with no luck.

My .overcommit.yml file looks like this:

```
PreCommit:
  Rubocop:
    enabled: false
CommitMsg:
  CommonCommit:
    enabled: true
    quiet: false
    description: 'Checks if the commit message follows the common commit specifications'
    required_executable: 'yarn'
    command: ['yarn', 'run', 'commitlint']
    flags: ['-e']
  TextWidth:
    enabled: false
```

I am running overcommit not from a globally installed gem but as a dev dependency inside my Gemfile. When I run `bundle exec overcommit -l', I will see CommonCommit listed and enabled

```
CommitMsg:
  GerritChangeId: disabled
  HardTabs: enabled
  RussianNovel: enabled
  SingleLineSubject: enabled
  TextWidth: disabled
  TrailingPeriod: enabled
  CommonCommit: enabled
```
And when I run `yarn run commitlint -e`, it will check my last commit message and fail, because it doesn't follow the specifications.

However, when I run `git commit --amend`, it will show me this:

```
Running commit-msg hooks
Checking for hard tabs.....................................[HardTabs] OK
Checking subject line.............................[SingleLineSubject] OK
Checking for trailing periods in subject.............[TrailingPeriod] OK
```
And CommonCommit is nowhere to be found. No error message, as if it was never there. Could this be a bug, or do you think I'm just not doing something properly?

**Comment by sds** [comment]
Not sure what the issue is, @camiloforero. I can't reproduce what you're seeing. This suggests to me that potentially the globally-installed `overcommit` gem you have is a very old version, or you are doing something else incorrectly.

When I have the following `.overcommit.yml`:
```
CommitMsg:
  CommonCommit:
    enabled: true
    quiet: false
    description: 'Checks if the commit message follows the common commit specifications'
    command: ['echo', 'hello']
```
...and I `git add ...` it and attempt to commit, I correctly see the output:

```
Running pre-commit hooks
(...omitted...)

✓ All pre-commit hooks passed

Running commit-msg hooks
Check subject capitalization.....................[CapitalizedSubject] OK
Check subject line................................[SingleLineSubject] OK
Check for trailing periods in subject................[TrailingPeriod] OK
Check text width..........................................[TextWidth] OK
Checks if the commit message follows the common commit specifications[CommonCommit] OK

⚠ All commit-msg hooks passed, but with warnings
```

I'm not sure what else to offer—this is a pretty straightforward example. Let us know what you discover.
