### ISSUE TITLE
Odd reek behavior with project

### ISSUE THREAD

**Issue by tleish** [sds/overcommit#664]
I have a puzzling scenario that I am unable to figure out.  I have the following reeky config.

I have the following inconsistent behaviors when running reek stand-alone vs via overcommit:
``` 
$ reek 
Inspecting 5 file(s):
...S.
lib/file_a.rb -- 1 warning:
    [126]:UtilityFunction: ....
```

``` 
$ git commit -m "fix reek warnings" 
Running pre-commit hooks
Check Gemfile dependencies..............................[BundleCheck] OK
Analyzing for potential speed improvements.................[Fasterer] OK
Check for vulnerable versions of gems...................[BundleAudit] OK
Analyze with Reek..............................................[Reek] FAILED
Errors on modified lines:
  lib/file_b.rb : UncommunicativeVariableName...

Analyze with RuboCop........................................[RuboCop] OK

✗ One or more pre-commit hooks failed
```
Running reek stand-alone vs overcommit shows different reek errors.  I trust the stand-alone, as it appears to be honoring my .reek.yml file.  Running reek through overcommit not only misses one of the reek errors, but it reports another that should be ignored based on my `.reek.yml` config.

```yaml
---
detectors:
  IrresponsibleModule:
    enabled: true
  UncommunicativeVariableName:
    enabled: false
```

I tried to reproduce this in a stand-alone project with just 1 file, but have been unable to reproduce this.  Any troubleshooting tips to narrow down the issue?

FYI, 
```
$ overcommit -v
overcommit 0.49.1
```

 `.overcommit.yml` file

```yaml
PreCommit:
  BundleCheck:
    enabled: true
    
  BundleAudit:
    enabled: true

  Reek:
    enabled: true

  RuboCop:
    enabled: true
    on_warn: fail

  Fasterer:
    enabled: true
```
