### ISSUE TITLE
Can't get RailsBestPractices to work

### ISSUE THREAD

**Issue by Diego-Zulu** [sds/overcommit#693]
Hey there, I can't get the `RailsBestPractices` hook to work at all

These are the steps I took so far:

1. `rails new overcommit-test` (with rails 6.0.0) and cd into the folder
2. `bundle add overcommit`
3. `bundle exec overcommit --install`
4. `bundle add rails_best_practices`
5. Remove all comments from `.overcommit.yml`, and then add these lines:
```
gemfile: Gemfile

PreCommit:
  ALL:
    on_warn: fail

  RailsBestPractices:
    enabled: true
```
6. `bundle exec overcommit --sign`
7. Run `bundle exec rails_best_practices`, and verify it's detecting the only offense that comes with a new rails application, `/overcommit-test/config/environments/test.rb:8 - remove trailing whitespace`
8. `git add .` to track all my unstaged files
9. `bundle exec overcommit --run` runs the RailsBestPractices hook. It should fail but passes
10. Then I try commiting. Commit should fail but still passes
11. I try `bundle exec overcommit --run` one more time, with same result. Hook runs but does not fail.

I read [the old issue that had a similar problem](https://github.com/sds/overcommit/issues/324), but that was solved by adding the `gemfile: Gemfile`, which I already did

Anybody knows what could be happening?

**Comment by sds** [comment]
I'm not familiar with this hook so I'm not sure what could be wrong on the surface. But given what we observed in #691, it may be due to a similar issue. Suggest you investigate further on your side to confirm if passing the explicit files causes differing behavior.

**Comment by Diego-Zulu** [comment]
Hey @sds ! Your were totally right, thanks for the help!

When I tried supplying the specific file with the issue with the `include` option in `.overcommit.yml`, both Fasterer and RailsBestPractices worked correctly!

I also discovered that this config makes them both work correctly:
```
gemfile: Gemfile

PreCommit:
  ALL:
    on_warn: fail

  RailsBestPractices:
    enabled: true
    command: ['rails_best_practices', '.']

  Fasterer:
    enabled: true
    command: ['fasterer', '.']
```
So if anybody needs a quick fix for any of these hooks, this should work for now!
