### ISSUE TITLE
pre-push custom script receives remote name and remote URL as arguments

### ISSUE THREAD

**Issue by kosmotaur** [sds/overcommit#696]
Hi!

I am using this as `.overcommit.yml`:

```yaml
PrePush:
  CustomScript:
    enabled: true
    command: ['bundle', 'exec', 'bin/test']
    flags: ['foo']

verify_signatures: false
```

When running my custom `test` script on pre-push, it receives this array as arguments (I removed the full URL on purpose):
`["foo", "origin", "git@github.com:[REDACTED]"]`

My test script starts with this line:
`#!/usr/bin/env ruby`

I read the arguments by calling
```ruby
puts ARGV.to_s
```
in my script

The additional git-specific arguments break my script, which treats the first argument as a path to run against, or default to CWD if there's no arguments present.
I could code around that, but unfortunately this also breaks when I'm trying to invoke Rubocop in a similar fashion:

```yaml
PrePush:
  CustomScript:
    enabled: true
    command: ['bundle', 'exec', 'rubocop']

verify_signatures: false
```

In this scenario, Rubocop finds 0 files, as the directory `origin` (again, coming in as some sort of git-specific argument) doesn't exist. Here's some output demonstrating that scenario:

```
~/src/website
❯ bundle exec rubocop app
Inspecting 63 files
...............................................................

63 files inspected, no offenses detected

~/src/website
❯ bundle exec rubocop origin
Inspecting 0 files


0 files inspected, no offenses detected
```

I don't seem to be able to find an option to prevent the git bits passed as arguments. Am I missing something?
