### ISSUE TITLE
Xcode could not be saved

### ISSUE THREAD

**Issue by ahmedAlmasri** [sds/overcommit#707]
Hello,

After added the overcommit file in my Xcode project,  all file after change showing this popup 

<img width="633" alt="Screen Shot 2020-03-04 at 8 48 54 PM" src="https://user-images.githubusercontent.com/14888785/75913130-09f04e80-5e5b-11ea-9925-d8807b97fd35.png">

**Comment by sds** [comment]
Which version of Overcommit are you running, @ahmedAlmasri? 

This shouldn't happen as of [Overcommit 0.51.0](https://github.com/sds/overcommit/releases/tag/v0.51.0) **unless** you are staging only a portion of the file. Otherwise, this is expected behavior since Overcommit stashes unstaged changes to the file so hooks are run only against staged changes.

**Comment by ahmedAlmasri** [comment]
@sds 
overcommit version 0.52.1
Xcode version 11.3.1

my yml file 


```
CommitMsg:
 MessageFormat:
    enabled: true
    description: 'Check commit message matches expected pattern'
    pattern: '(\[issue-[0-9]+\]\-\[(WIP|DONE)\]\-.+|merge)'
    expected_pattern_message: '[Issue Id]-[Status]-<Commit Message Description>'
    sample_message: '[issue-1234]-[DONE]-Your message or [issue-1234]-[WIP]-Your message '

PreCommit:

  SwiftLint:
    enabled: true
    description: 'Analyze with SwiftLint'
    required_executable: 'swiftlint'
    flags: ['lint', '--strict']
    include: '**/*.swift'
```
This issue appears after fixing errors for swiftlint
