### ISSUE TITLE
PostCheckout Rake Task

### ISSUE THREAD

**Issue by tleish** [sds/overcommit#716]
Since there's no hook for running a rake task on PostCheckout, I'm attempting to run a custom script:

```yaml
PostCheckout:
  MyTask:
    command: ['bundle', 'exec', 'rake', 'my:task']
    enabled: true
```
I am getting rake errors when running this task:

```
Running post-checkout hooks
Run MyTask...........................................[MyTask] FAILED
rake aborted!
Don't know how to build task '07e564aaf6511451be221bb783189257f3cee1b3' (See the list of available tasks with `rake --tasks`)
/Users/username/.asdf/installs/ruby/2.6.5/bin/bundle:23:in `load'
/Users/username/.asdf/installs/ruby/2.6.5/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

Is there a better way to run a PostCheckout rake task?

**Comment by sds** [comment]
When you create an ad hoc hook in this way, you are telling Overcommit to execute the hook as if it were an actual Git hook. `post-checkout` hooks receive [three parameters as discussed in the documentation](https://git-scm.com/docs/githooks#_post_checkout).

The argument you are seeing to rake is one of those hooks. A simple workaround would be to invoke a shell script that ignores the arguments and invokes your command directly:

```yaml
PostCheckout:
  MyTask
    command: ['sh', '-c', 'exec bundle exec rake my:task']
    enabled: true
```

Hope that clarifies.
