### ISSUE TITLE
Overcommit taking long time to exit

### ISSUE THREAD

**Issue by aes421** [sds/overcommit#720]
I am new to overcommit, so it's likely I'm doing something wrong.

In a post commit hook I am trying to generate new files then add them to the previous commit.  The functionality works perfect (files are generated, staged, and then amended to the commit).  However, overcommit takes ~10 minutes to exit.  If I use ctrl+c to exit then everything is fine because the commit hook did work correctly.  I am stuck at this stage:
![image](https://user-images.githubusercontent.com/10823042/85209072-a51e0e80-b2fa-11ea-9e5a-36c5ed09864e.png)

Here is my overcommit.yml
```yaml
PostCommit:
    GeneratePages:
        enabled: true
        command: ['python', 'generator.py']
    AddTags:
        enabled: true
        command: ['git', 'add', './_tag-entries']
    AmendCommit:
        enabled: true
        command: ['git', 'commit', '--amend', '--no-edit']
```

**Comment by sds** [comment]
Hey @aes421, I don't have an immediate answer to why your hook runs take 10 minutes. That is certainly odd.

With that said, `post-commit` hooks _are_ run after commit, so the fact that you are not seeing their output until 10 minutes later suggests it is one of your hooks. You can set the `OVERCOMMIT_DEBUG=1` environment variable to get timing information so you can understand which hook is the slow one.

Also note: as discussed in #238 Overcommit does not support `pre-commit` hooks with file-changing side-effects. In this case, I'm not aware of anything preventing this working with `post-commit` hooks, but I personally haven't tried. Just want you to be aware that there may be some other issue with what you are trying to do. 

Hope this helps! I'm going to close in the meantime as I'm pretty sure this is something to do with the `python generator.py` command, as that seems like something that could suspiciously take a long time. Feel free to reopen if you discover something suggestion this is Overcommit. Thanks!

**Comment by pillarsdotnet** [comment]
@sds

I ran into the same problem as @aes421 -- I think it happens because the `post-commit` hook has a `git commit` command, which calls overcommit, which calls the `post-commit` hook recursively.

I did the following, which seems to be working:

```
PostCommit:
  GenerateDocs:
    enabled: true
    command: ['bash', '-c', 'overcommit -u ; puppet strings generate --format markdown ; git add REFERENCE.md ; git commit REFERENCE.md --amend --no-edit ; overcommit -i']
```

**Comment by sds** [comment]
You could also set `OVERCOMMIT_DISABLE=1` instead of `overcommit -u` / `overcommit -i` to avoid uninstalling/reinstalling the hooks. But I'll emphasize this isn't a supported workflow today.

**Comment by aes421** [comment]
Changing my post commit hook to the following as @pillarsdotnet mentioned works.
```
PostCommit:
    GenerateTagPages:
        enabled: true
        command: ['python', 'tag-generator.py']
    AmendCommit:
        enabled: true
        command: ['bash', '-c', 'overcommit -u; git add ./_tag-entries; git commit --amend --no-edit; overcommit -i;']
```

I tried using
`command: ['bash', '-c', 'OVERCOMMIT_DISABLE=1 git add ./_tag-entries; git commit --amend --no-edit;']`
since it looks cleaner, but it still caused an infinite loop.

I also tried
`command: ['OVERCOMMIT_DISABLE=1 git add ./_tag-entries; git commit --amend --no-edit;']`
but I get the error FAILED
'"OVERCOMMIT_DISABLE' is not recognized as an internal or external command,
operable program or batch file.
