### ISSUE TITLE
What are valid commit types for `PrepareCommitMsg.ReplaceBranch.skipped_commit_types`?

### ISSUE THREAD

**Issue by 34875634567** [sds/overcommit#724]
I'm having trouble getting this hook to run only when 'manually' committing, and not during rebase/amend etc.

It looks like functionality to support this was introduced in https://github.com/sds/overcommit/commit/d46dbf0d918fa208c83fa801fe75c7c06e07c7d9, but it's not clear what the supported options are.

The following examples are given in [default.yaml](https://github.com/sds/overcommit/blob/b70cefcc992b109ca9905b4653a7cf2751f56fff/config/default.yml), are there others?
```
PrepareCommitMsg:
  ReplaceBranch:
    enabled: false
    description: 'Prepends the commit message with text based on the branch name'
    branch_pattern: '\A.*\w+[-_](\d+).*\z'
    replacement_text: '[#\1]'
    skipped_commit_types: ['message', 'template', 'merge', 'squash']
    on_fail: warn
```
