### ISSUE TITLE
Overcommit + Rubocop ignoring .rubocop_todo.yml? 

### ISSUE THREAD

**Issue by etagwerker** [sds/overcommit#733]
Hi there, 

First of all thanks for maintaining this project! It's been very useful for years! 😄 

I ran into a weird issue with `rubocop` and its `.rubocop_todo.yml` when trying to `git commit` a few changes. 

## Versions 

I'm using these versions: 

- overcommit v0.57.0
- rubocop v0.92.0

## .rubocop_todo.yml 

This is what my TODO file looks like: 

```yaml
# This configuration was generated by
# `rubocop --auto-gen-config`
# on 2020-10-18 02:04:40 UTC using RuboCop version 0.91.1.
# The point is for the user to remove these configuration records
# one by one as the offenses are removed from the code base.
# Note that changes in the inspected code, or installation of new
# versions of RuboCop, may require this file to be generated again.

# Offense count: 2
# Cop supports --auto-correct.
OmbuLabs/Branding:
  Exclude:
    - 'app/mailers/contact_mailer.rb'
    - 'app/mailers/roadmap_mailer.rb'

# Offense count: 1
# Configuration parameters: Max.
RSpec/ExampleLength:
  Exclude:
    - 'spec/controllers/newsletter_controller_spec.rb'

# Offense count: 1
RSpec/MultipleExpectations:
  Max: 5
```

## .overcommit.yml

This is what my configuration file looks like: 

```yaml
CommitMsg:
  CapitalizedSubject:
    enabled: false
  EmptyMessage:
    enabled: false
  TrailingPeriod:
    enabled: true
  TextWidth:
    enabled: false

PreCommit:
  ALL:
    on_warn: fail
  AuthorEmail:
    enabled: true
  AuthorName:
    enabled: true
  MergeConflicts:
    enabled: true
  YamlSyntax:
    enabled: true
  BundleCheck:
    enabled: true
  RuboCop:
    enabled: true
  Reek:
    enabled: true
  RailsBestPractices:
    enabled: true
```

## Current behavior

When I try to commit I get a rubocop error: 

```
git commit app config public spec
Running pre-commit hooks
Check YAML syntax........................................[YamlSyntax] OK
Analyze with RuboCop........................................[RuboCop] FAILED
Errors:
Errors on modified lines:
/Users/etagwerker/Projects/ombulabs/fastruby.io/app/mailers/contact_mailer.rb:6:14: C: OmbuLabs/Branding: Wrong branding, use "OmbuLabs"
/Users/etagwerker/Projects/ombulabs/fastruby.io/app/mailers/roadmap_mailer.rb:5:20: C: OmbuLabs/Branding: Wrong branding, use "OmbuLabs"
Errors on lines you didn't modify:
/Users/etagwerker/Projects/ombulabs/fastruby.io/spec/controllers/newsletter_controller_spec.rb:15:5: C: RSpec/ExampleLength: Example has too many lines [6/5].
/Users/etagwerker/Projects/ombulabs/fastruby.io/spec/controllers/newsletter_controller_spec.rb:15:5: C: RSpec/MultipleExpectations: Example has too many expectations [5/1].
✗ One or more pre-commit hooks failed
```

## Expected behavior 

I was expecting it to work. When I run `rubocop` without `overcommit` I don't get the same errors (because `rubocop` uses the `.rubocop_todo.yml` which excludes the cops: 

```
$ bundle exec rubocop app/mailers/contact_mailer.rb app/mailers/roadmap_mailer.rb spec/controllers/newsletter_controller_spec.rb
Inspecting 3 files
...

3 files inspected, no offenses detected
```

I assume that there is something that I'm doing wrong. Does anything stand out?
