### ISSUE TITLE
eslint rule will fail due to filepaths that contain either "Warning" or "Error"

### ISSUE THREAD

**Issue by adamvonbaron** [sds/overcommit#743]
hi there,

my team uses overcommit to check our typescript codebase with eslint using the included [eslint rule](https://github.com/sds/overcommit/blob/master/lib/overcommit/hook/pre_commit/es_lint.rb). we discovered an issue with overcommit reporting an error on the eslint step, however running eslint by itself didnt show any errors. what we believe is happening is overcommit will parse the output of an eslint command that runs on a file or directory that contains the word "Error" or "Warning" as an actual error reported by eslint. the first case shows expected behavior, the second case shows the issue:

```bash
(base) apk@wolfenstein:~/Source/project(test-branch○) » touch error.ts
(base) apk@wolfenstein:~/Source/project(test-branch⚡) » git add error.ts
(base) apk@wolfenstein:~/Source/project(test-branch⚡) » git commit -m "test"
Running pre-commit hooks
Ensure eslint is used to lint JS.............................[EsLint] OK

✓ All pre-commit hooks passed

[test-branch b84f0904e] test
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 error.ts
```

```bash
(base) apk@wolfenstein:~/Source/project(test-branch○) » touch Error.ts
(base) apk@wolfenstein:~/Source/project(test-branch⚡) » git add Error.ts
(base) apk@wolfenstein:~/Source/project(test-branch⚡) » git commit -m "test"
Running pre-commit hooks
Ensure eslint is used to lint JS.............................[EsLint] FAILED
Unexpected output: unable to determine line number or type of error/warning for output:
$ yarn eslint --quiet --format=compact /Users/apk/Source/project/Error.ts
$ /Users/apk/Source/project/node_modules/.bin/eslint --quiet --format=compact /Users/apk/Source/project/Error.ts

✗ One or more pre-commit hooks failed
```

this line seems to be the culprit:

https://github.com/sds/overcommit/blob/bba5b75b2c16efccf2dbbbe4f2af103a15011119/lib/overcommit/hook/pre_commit/es_lint.rb#L24-L26

here is our .overcommit.yml for reference:

```yaml
EsLint:
    required_executable: "yarn"
    enabled: true
    command: ["yarn"]
    flags: ["eslint", "--quiet", "--format=compact"]
    description: "Ensure eslint is used to lint JS"
    exclude:
      - "/typings/**/*.d.ts"
    include:
      - "**/*.ts"
      - "**/*.tsx"
```
is it possible for overcommit to differentiate between what the current command running is, and the actual output of the command itself? that looks like the crux of the problem; it will parse both the command and it's output using the same rule.
