### ISSUE TITLE
permissions / no-permissions deadlock

### ISSUE THREAD

**Issue by andreheijstek** [sds/overcommit#768]
I am trying to add a custom hook to overcommit using:
```
CustomScript:
enabled: true
required_executable: "./.git-hook/i18n-missing"
```
The .git-hook directory is in my PATH.
If the i18n-missing file has no execute permissions, I get the following error:
`'./.git-hook/i18n-missing' is not installed, not in your PATH, or does not have execute permissions`
If I give it execute permissions, I get:
`File .git-hook/i18n-missing has unnecessary execute permissions`

How to escape from this?

**Comment by sds** [comment]
Apologies for the delay in response.

Simply add the file to be ignored by the `ExecutePermissions` check:

**.overcommit.yml**
```yaml
  ExecutePermissions:
    enabled: true
    exclude: './.git-hook/i18n-missing'
```

...or similar.

Hope that helps.
