### ISSUE TITLE
Failure running Stylelint

### ISSUE THREAD

**Issue by afdev82** [sds/overcommit#775]
I'm getting the error

```
Unexpected output: unable to determine line number or type of error/warning for output:
```

if I enable in this way the Stylelint precommit hook:

```
PreCommit:
  Stylelint:
    required_executable: 'yarn'
    enabled: true
    command: ['yarn', 'run', 'stylelint']
    include:
      - 'app/assets/stylesheets/**/*'
```

I'm using the version 14.6.1:

```
$ yarn info stylelint version
yarn info v1.22.17
14.6.1
```

Thank you for your support!
