### ISSUE TITLE
Errors are output twice for erblint pre-commit hook

### ISSUE THREAD

**Issue by jameshibbard** [sds/overcommit#792]
Hi,

When I run erb-lint from the command line, errors are output as expected:

```
bundle exec erblint app/views 
Linting 24 files with 17 linters...

Use 1 space after `<%=` instead of 0 space.
In file: app/views/applicants/index.html.erb:10

Use 1 space after `<%=` instead of 0 space.
In file: app/views/layouts/application.html.erb:29
```

However, when run by overcommit as a pre-commit hook, each error is output twice. E.g.:

```
g commit -m "This should fail"

Analyze with ERB Lint.......................................[ErbLint] FAILED
Errors on modified lines:
Use 1 space after `<%=` instead of 0 space.
In file: app/views/applicants/index.html.erb:10
Use 1 space after `<%=` instead of 0 space.
In file: app/views/applicants/index.html.erb:10
Use 1 space after `<%=` instead of 0 space.
In file: app/views/layouts/application.html.erb:29
Use 1 space after `<%=` instead of 0 space.
In file: app/views/layouts/application.html.erb:29

✗ One or more pre-commit hooks failed
```

I have the following in `.overcommit.yml`:

```
ErbLint:
  enabled: true
  on_warn: fail
  problem_on_unmodified_line: ignore
  command: ['bundle', 'exec', 'erblint', 'app/views']
```

Could you give me an idea as to what I am doing wrong? 

It would be great to see each error only once.

---

**Edit**:

FWIW, altering [the hook](https://github.com/sds/overcommit/blob/master/lib/overcommit/hook/pre_commit/erb_lint.rb) to call `uniq` on the `extract_messages` method makes the problem go away:

```
extract_messages(
  result.stdout.split("\n\n")[1..-1],
  MESSAGE_REGEX
).uniq
```

But I can't imagine that is the correct fix.

**Comment by jameshibbard** [comment]
Sorry, figured it out.

The default config is:

```
ErbLint:
  enabled: false
  description: 'Analyze with ERB Lint'
  required_executable: 'erblint'
  install_command: 'bundle install erb_lint'
  include: '**/*.html.erb'
```

So I only needed to do this:

```
ErbLint:
  enabled: true
  command: ['bundle', 'exec', 'erblint']
```

And errors are output only once.
