### ISSUE TITLE
I need help in pointing rubocop.yml to overcommit hook

### ISSUE THREAD

**Issue by Affan1202o** [sds/overcommit#793]
I'm currrently using overcommit to handle all my precommit hooks , this is what my current overcommit.yml file looks 

PreCommit:
  RuboCop:
    enabled: true
    required_executable: ~/.rbenv/shims/rubocop
    required_library: 
    on_warn: fail # Treat all warnings as failures
    problem_on_unmodified_line: ignore # run RuboCop only on modified code
    command: ['bundle','exec','rubocop']
    
    How do I point overcommit.yml to .rubocop.yml so that I can add and remove cops in .rubocop.yml ?

**Comment by sds** [comment]
RuboCop should be loading the correct `.rubocop.yml` automatically. If you need to specify a custom location, add `--config path/to/rubocop.yml` to the `flags` option for your `RuboCop` hook configuration:

```yaml
PreCommit:
  RuboCop:
    enabled: true
    flags: ['--format=emacs', '--force-exclusion', '--display-cop-names', '--config', 'path/to/file'] 
```
