### ISSUE TITLE
Exclude not working on PreCommit hook

### ISSUE THREAD

**Issue by iamnewton** [sds/overcommit#83]
**.overcommit.yml**

``` yml
PreCommit:
  ALL:
    exclude:
      - '**/node_modules/**'
      - '**/www/vendor/**'
```

**Project Directory Structure**

``` bash
- .overcommit.yml
- node_modules/
- www/
  - vendor/
```

Given the example YML config and project structure, shouldn't all Pre-Commit hooks not be run on anything in the `node_modules` and `www/vendor` directories?  Because it fails on all of those.
