### ISSUE TITLE
Overcommit treating entire repository as modified

### ISSUE THREAD

**Issue by mbajur** [sds/overcommit#855]
Hey! I'm trying to enable overcommit with rubocop for my repository and here is my config:

```
PreCommit:
 RuboCop:
   enabled: true
   command: ['bundle', 'exec', 'rubocop']
   problem_on_unmodified_line: warn
```

And the problem is, even though `.overcommit.yml` file is the only modified file in that branch, running `overcommit --run` is giving me rubocop errors for every single rubocop violation on my branch/repo. It's like `problem_on_unmodified_line: warn` line is being ignored and full rubocop check is being triggered.

I'm on overcommit 0.64.0 / rubocop 1.57.2
